CREATE TABLE "users" (
  "user" varchar PRIMARY KEY,
  "name" varchar(50) NOT NULL,
  "password" varchar NOT NULL
);

CREATE TABLE "category" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(100) NOT NULL,
  "color" varchar(7) NOT NULL,
  "icon" varchar,
  "type" varchar,
  "id_user" varchar
);

CREATE TABLE "expenses" (
  "date" date NOT NULL,
  "total" double NOT NULL,
  "concept" varchar,
  "id_category" int,
  "id_user" varchar
);

CREATE TABLE "budget" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_user" varchar,
  "month" date NOT NULL,
  "total" double NOT NULL
);

CREATE UNIQUE INDEX ON "category" ("id_user", "name");

CREATE UNIQUE INDEX ON "budget" ("id_user", "month");

COMMENT ON COLUMN "budget"."month" IS 'primer dia del mes';

ALTER TABLE "expenses" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("user") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "expenses" ADD FOREIGN KEY ("id_category") REFERENCES "category" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "category" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("user") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "budget" ADD FOREIGN KEY ("id_user") REFERENCES "users" ("user") DEFERRABLE INITIALLY IMMEDIATE;
